# Generated by Django 5.1 on 2025-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_disciplinas_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noturno'), ('S', 'Superior')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('cargaHoraria', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=255)),
            ],
        ),
    ]
